/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HandwritingGeneratorRouteImport } from './routes/handwriting-generator'
import { Route as HandwrittenAssignmentGeneratorRouteImport } from './routes/handwritten-assignment-generator'
import { Route as HandwrittenMathGeneratorRouteImport } from './routes/handwritten-math-generator'
import { Route as HandwrittenNotesGeneratorRouteImport } from './routes/handwritten-notes-generator'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TextToHandwritingRouteImport } from './routes/text-to-handwriting'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedEditorProjectIdRouteImport } from './routes/_authenticated/editor.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HandwritingGeneratorRoute = HandwritingGeneratorRouteImport.update({
  id: '/handwriting-generator',
  path: '/handwriting-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const HandwrittenAssignmentGeneratorRoute =
  HandwrittenAssignmentGeneratorRouteImport.update({
    id: '/handwritten-assignment-generator',
    path: '/handwritten-assignment-generator',
    getParentRoute: () => rootRouteImport,
  } as any)
const HandwrittenMathGeneratorRoute =
  HandwrittenMathGeneratorRouteImport.update({
    id: '/handwritten-math-generator',
    path: '/handwritten-math-generator',
    getParentRoute: () => rootRouteImport,
  } as any)
const HandwrittenNotesGeneratorRoute =
  HandwrittenNotesGeneratorRouteImport.update({
    id: '/handwritten-notes-generator',
    path: '/handwritten-notes-generator',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TextToHandwritingRoute = TextToHandwritingRouteImport.update({
  id: '/text-to-handwriting',
  path: '/text-to-handwriting',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEditorProjectIdRoute =
  AuthenticatedEditorProjectIdRouteImport.update({
    id: '/editor/$projectId',
    path: '/editor/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/handwriting-generator': typeof HandwritingGeneratorRoute
  '/handwritten-assignment-generator': typeof HandwrittenAssignmentGeneratorRoute
  '/handwritten-math-generator': typeof HandwrittenMathGeneratorRoute
  '/handwritten-notes-generator': typeof HandwrittenNotesGeneratorRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/text-to-handwriting': typeof TextToHandwritingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/editor/$projectId': typeof AuthenticatedEditorProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/handwriting-generator': typeof HandwritingGeneratorRoute
  '/handwritten-assignment-generator': typeof HandwrittenAssignmentGeneratorRoute
  '/handwritten-math-generator': typeof HandwrittenMathGeneratorRoute
  '/handwritten-notes-generator': typeof HandwrittenNotesGeneratorRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/text-to-handwriting': typeof TextToHandwritingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/editor/$projectId': typeof AuthenticatedEditorProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/handwriting-generator': typeof HandwritingGeneratorRoute
  '/handwritten-assignment-generator': typeof HandwrittenAssignmentGeneratorRoute
  '/handwritten-math-generator': typeof HandwrittenMathGeneratorRoute
  '/handwritten-notes-generator': typeof HandwrittenNotesGeneratorRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/text-to-handwriting': typeof TextToHandwritingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/editor/$projectId': typeof AuthenticatedEditorProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/faq'
    | '/handwriting-generator'
    | '/handwritten-assignment-generator'
    | '/handwritten-math-generator'
    | '/handwritten-notes-generator'
    | '/privacy'
    | '/terms'
    | '/text-to-handwriting'
    | '/dashboard'
    | '/settings'
    | '/editor/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/faq'
    | '/handwriting-generator'
    | '/handwritten-assignment-generator'
    | '/handwritten-math-generator'
    | '/handwritten-notes-generator'
    | '/privacy'
    | '/terms'
    | '/text-to-handwriting'
    | '/dashboard'
    | '/settings'
    | '/editor/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/faq'
    | '/handwriting-generator'
    | '/handwritten-assignment-generator'
    | '/handwritten-math-generator'
    | '/handwritten-notes-generator'
    | '/privacy'
    | '/terms'
    | '/text-to-handwriting'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_authenticated/editor/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FaqRoute: typeof FaqRoute
  HandwritingGeneratorRoute: typeof HandwritingGeneratorRoute
  HandwrittenAssignmentGeneratorRoute: typeof HandwrittenAssignmentGeneratorRoute
  HandwrittenMathGeneratorRoute: typeof HandwrittenMathGeneratorRoute
  HandwrittenNotesGeneratorRoute: typeof HandwrittenNotesGeneratorRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TextToHandwritingRoute: typeof TextToHandwritingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handwriting-generator': {
      id: '/handwriting-generator'
      path: '/handwriting-generator'
      fullPath: '/handwriting-generator'
      preLoaderRoute: typeof HandwritingGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handwritten-assignment-generator': {
      id: '/handwritten-assignment-generator'
      path: '/handwritten-assignment-generator'
      fullPath: '/handwritten-assignment-generator'
      preLoaderRoute: typeof HandwrittenAssignmentGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handwritten-math-generator': {
      id: '/handwritten-math-generator'
      path: '/handwritten-math-generator'
      fullPath: '/handwritten-math-generator'
      preLoaderRoute: typeof HandwrittenMathGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handwritten-notes-generator': {
      id: '/handwritten-notes-generator'
      path: '/handwritten-notes-generator'
      fullPath: '/handwritten-notes-generator'
      preLoaderRoute: typeof HandwrittenNotesGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-to-handwriting': {
      id: '/text-to-handwriting'
      path: '/text-to-handwriting'
      fullPath: '/text-to-handwriting'
      preLoaderRoute: typeof TextToHandwritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/editor/$projectId': {
      id: '/_authenticated/editor/$projectId'
      path: '/editor/$projectId'
      fullPath: '/editor/$projectId'
      preLoaderRoute: typeof AuthenticatedEditorProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedEditorProjectIdRoute: typeof AuthenticatedEditorProjectIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedEditorProjectIdRoute: AuthenticatedEditorProjectIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FaqRoute: FaqRoute,
  HandwritingGeneratorRoute: HandwritingGeneratorRoute,
  HandwrittenAssignmentGeneratorRoute: HandwrittenAssignmentGeneratorRoute,
  HandwrittenMathGeneratorRoute: HandwrittenMathGeneratorRoute,
  HandwrittenNotesGeneratorRoute: HandwrittenNotesGeneratorRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TextToHandwritingRoute: TextToHandwritingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
